
// service/codeExport.ts

declare const JSZip: any;

export const downloadProjectZip = async () => {
  if (typeof JSZip === 'undefined') {
    alert("Erreur: La librairie de compression n'est pas chargée. Rafraichissez la page.");
    return;
  }

  const zip = new JSZip();

  // 1. README.md
  const readme = `# VTV Streaming Platform

Voici le code source complet de votre plateforme VTV prêt à être déployé.

## 🚀 Déploiement Rapide (GitHub Pages)

1. Créez un repository sur GitHub.
2. Uploadez ces fichiers (index.html, style.css, script.js).
3. Allez dans Settings > Pages.
4. Activez la source sur "main".

Votre site sera en ligne en quelques secondes !

## 📂 Contenu

Ce site est une "Single Page Application" autonome écrite en HTML/CSS/JS pur.
Elle n'a pas besoin de serveur backend (les données sont stockées dans le navigateur du visiteur ou de l'admin).
`;

  zip.file("README.md", readme);

  // 2. index.html
  const indexHtml = `<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>VTV - Streaming Premium</title>
    <meta name="theme-color" content="#00CEC8">
    
    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>
    
    <!-- Icons -->
    <script src="https://unpkg.com/lucide@latest"></script>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>
<body class="bg-neutral-950 text-white font-inter overflow-x-hidden selection:bg-[#00CEC8] selection:text-black">
    <div id="app"></div>
    <script src="script.js"></script>
</body>
</html>`;

  zip.file("index.html", indexHtml);

  // 3. style.css
  const styleCss = `
body { font-family: 'Inter', sans-serif; background-color: #0a0a0a; overscroll-behavior-y: none; }

::-webkit-scrollbar { width: 8px; }
::-webkit-scrollbar-track { background: #0a0a0a; }
::-webkit-scrollbar-thumb { background: #333; border-radius: 4px; }

.logo-shine {
    color: #00CEC8;
    text-shadow: 0 0 10px rgba(0, 206, 200, 0.5);
    animation: glow 3s ease-in-out infinite alternate;
}
@keyframes glow {
    from { text-shadow: 0 0 5px rgba(0, 206, 200, 0.2); }
    to { text-shadow: 0 0 20px rgba(0, 206, 200, 0.6); }
}

.scrollbar-hide::-webkit-scrollbar { display: none; }
.scrollbar-hide { -ms-overflow-style: none; scrollbar-width: none; }

.animate-fade-in { animation: fadeIn 0.5s ease-out; }
@keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
`;

  zip.file("style.css", styleCss);

  // 4. script.js (Logic Port)
  const scriptJs = `
/**
 * VTV STATIC LOGIC
 * Generated by Admin Export
 */

const PLANS = {
    'BASIC': { price: "5 500 FCA", name: "Basic" },
    'STANDARD': { price: "10 500 FCA", name: "Standard" },
    'PREMIUM': { price: "15 000 FCA", name: "Premium" },
};
const ADMIN_EMAIL = "victormelchior92@gmail.com";
const ADMIN_PIN = "2008";
const PAYMENT_NUMBER = "+241 07 40 87 064";

const state = {
    user: null,
    users: [],
    content: [],
    categories: [],
    suggestions: [],
    theme: 'DEFAULT',
    activeTab: 'CONTENT',
    searchQuery: '',
    communityLink: ''
};

// --- DATABASE ---
const db = {
    load: () => {
        state.users = JSON.parse(localStorage.getItem('vtv_users') || '[]');
        state.content = JSON.parse(localStorage.getItem('vtv_content') || '[]');
        state.categories = JSON.parse(localStorage.getItem('vtv_categories') || '[]');
        state.suggestions = JSON.parse(localStorage.getItem('vtv_suggestions') || '[]');
        state.communityLink = JSON.parse(localStorage.getItem('vtv_community_link') || '""');
        state.theme = localStorage.getItem('vtv_theme') || 'DEFAULT';
        
        const currentUser = JSON.parse(localStorage.getItem('vtv_current_user') || 'null');
        if (currentUser) {
            const fresh = state.users.find(u => u.id === currentUser.id);
            state.user = fresh || currentUser; 
        }
    },
    save: (key) => {
        if(key === 'users') localStorage.setItem('vtv_users', JSON.stringify(state.users));
        if(key === 'content') localStorage.setItem('vtv_content', JSON.stringify(state.content));
        if(key === 'categories') localStorage.setItem('vtv_categories', JSON.stringify(state.categories));
        if(key === 'suggestions') localStorage.setItem('vtv_suggestions', JSON.stringify(state.suggestions));
        if(key === 'community') localStorage.setItem('vtv_community_link', JSON.stringify(state.communityLink));
        if(key === 'theme') localStorage.setItem('vtv_theme', state.theme);
        if(state.user) localStorage.setItem('vtv_current_user', JSON.stringify(state.user));
    }
};

// --- RENDER ---
const app = document.getElementById('app');

function render() {
    app.innerHTML = '';
    
    let bgClass = "bg-neutral-950";
    if (state.theme === 'CHRISTMAS') bgClass = "bg-gradient-to-b from-green-900 to-red-950";
    else if (state.theme === 'HALLOWEEN') bgClass = "bg-gradient-to-b from-orange-900 to-purple-950";
    
    app.className = \`min-h-screen text-white \${bgClass} transition-colors\`;

    if (!state.user) renderAuth();
    else if (state.user.email === ADMIN_EMAIL && state.user.id !== 'admin-preview') renderAdmin();
    else renderUser();
    
    if(window.lucide) lucide.createIcons();
}

function renderAuth() {
    app.innerHTML = \`
        <div class="min-h-screen flex flex-col items-center justify-center p-6 bg-[url('https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85')] bg-cover relative">
            <div class="absolute inset-0 bg-black/80"></div>
            <div class="relative z-10 w-full max-w-md">
                <div class="text-center mb-8">
                    <h1 class="text-6xl font-black text-[#00CEC8] tracking-tighter logo-shine">VTV</h1>
                    <p class="text-gray-400">Premium Streaming</p>
                </div>
                <div id="auth-box" class="bg-neutral-900/90 backdrop-blur p-8 rounded-2xl border border-neutral-800 shadow-2xl">
                    <h2 class="text-2xl font-bold mb-4">Connexion</h2>
                    <form onsubmit="doLogin(event)" class="space-y-4">
                        <input id="email" type="email" placeholder="Email" class="w-full p-3 bg-black border border-neutral-700 rounded text-white" required>
                        <input id="pass" type="password" placeholder="Mot de passe" class="w-full p-3 bg-black border border-neutral-700 rounded text-white" required>
                        <button type="submit" class="w-full py-3 bg-[#00CEC8] text-black font-bold rounded">Se connecter</button>
                    </form>
                    <div class="mt-4 flex justify-between text-sm">
                        <button onclick="toggleRegister()" class="text-[#00CEC8]">Créer un compte</button>
                        <button onclick="toggleAdmin()" class="text-neutral-500">Admin</button>
                    </div>
                </div>
            </div>
        </div>
    \`;
}

function toggleRegister() {
    const box = document.getElementById('auth-box');
    box.innerHTML = \`
        <h2 class="text-2xl font-bold mb-4">Inscription</h2>
        <form onsubmit="doRegister(event)" class="space-y-4">
            <input id="reg-name" type="text" placeholder="Nom" class="w-full p-3 bg-black border border-neutral-700 rounded text-white" required>
            <input id="reg-email" type="email" placeholder="Email" class="w-full p-3 bg-black border border-neutral-700 rounded text-white" required>
            <input id="reg-pass" type="password" placeholder="Mot de passe" class="w-full p-3 bg-black border border-neutral-700 rounded text-white" required>
            <button type="submit" class="w-full py-3 bg-[#00CEC8] text-black font-bold rounded">S'inscrire</button>
        </form>
        <button onclick="renderAuth()" class="mt-4 text-sm text-neutral-400 w-full">Retour</button>
    \`;
}

function toggleAdmin() {
    const box = document.getElementById('auth-box');
    box.innerHTML = \`
        <h2 class="text-2xl font-bold mb-4 text-[#00CEC8]">Admin</h2>
        <form onsubmit="doAdminLogin(event)" class="space-y-4">
            <input id="adm-email" type="email" placeholder="Email" class="w-full p-3 bg-black border border-neutral-700 rounded text-white" required>
            <input id="adm-pin" type="password" placeholder="PIN" class="w-full p-3 bg-black border border-neutral-700 rounded text-white" required>
            <button type="submit" class="w-full py-3 bg-[#00CEC8] text-black font-bold rounded">Accéder</button>
        </form>
        <button onclick="renderAuth()" class="mt-4 text-sm text-neutral-400 w-full">Retour</button>
    \`;
}

// --- LOGIC ---
window.doLogin = (e) => {
    e.preventDefault();
    const email = document.getElementById('email').value;
    const pass = document.getElementById('pass').value;
    const u = state.users.find(x => x.email.toLowerCase() === email.toLowerCase() && x.password === pass);
    if(u) { state.user = u; db.save('user'); render(); }
    else alert("Erreur identifiants");
};

window.doRegister = (e) => {
    e.preventDefault();
    const name = document.getElementById('reg-name').value;
    const email = document.getElementById('reg-email').value;
    const pass = document.getElementById('reg-pass').value;
    if(state.users.find(x => x.email === email)) return alert("Email pris");
    const newUser = { id: Date.now().toString(), name, email, password: pass, status: 'GUEST', dateJoined: new Date().toISOString(), notifications: [] };
    state.users.push(newUser); db.save('users');
    state.user = newUser; db.save('user');
    render();
};

window.doAdminLogin = (e) => {
    e.preventDefault();
    if(document.getElementById('adm-email').value === ADMIN_EMAIL && document.getElementById('adm-pin').value === ADMIN_PIN) {
        state.user = { id: 'admin', name: 'Admin', email: ADMIN_EMAIL }; db.save('user'); render();
    } else alert("Erreur");
};

window.logout = () => { state.user = null; localStorage.removeItem('vtv_current_user'); render(); };

// --- ADMIN UI ---
function renderAdmin() {
    app.innerHTML = \`
        <div class="flex h-screen bg-neutral-900 overflow-hidden">
            <aside class="w-64 bg-black border-r border-neutral-800 flex flex-col p-4">
                <h1 class="text-2xl font-black text-[#00CEC8] mb-8 logo-shine px-2">VTV ADMIN</h1>
                <nav class="space-y-2 flex-1">
                    <button onclick="state.activeTab='CONTENT';render()" class="w-full text-left p-3 rounded font-bold \${state.activeTab==='CONTENT'?'bg-[#00CEC8] text-black':'text-gray-400'}">Contenu</button>
                    <button onclick="state.activeTab='USERS';render()" class="w-full text-left p-3 rounded font-bold \${state.activeTab==='USERS'?'bg-[#00CEC8] text-black':'text-gray-400'}">Abonnés</button>
                    <button onclick="state.activeTab='THEME';render()" class="w-full text-left p-3 rounded font-bold \${state.activeTab==='THEME'?'bg-[#00CEC8] text-black':'text-gray-400'}">Options</button>
                </nav>
                <button onclick="previewSite()" class="w-full py-2 border border-neutral-700 text-white rounded mb-2">Voir Site</button>
                <button onclick="logout()" class="w-full py-2 text-red-500">Déconnexion</button>
            </aside>
            <main class="flex-1 overflow-y-auto p-8" id="admin-panel"></main>
        </div>
    \`;
    renderAdminPanel();
}

function renderAdminPanel() {
    const p = document.getElementById('admin-panel');
    if(state.activeTab === 'CONTENT') {
        p.innerHTML = \`
            <div class="flex justify-between mb-6">
                <h2 class="text-3xl font-bold">Contenu</h2>
                <button onclick="openAddModal()" class="bg-[#00CEC8] text-black px-6 py-2 rounded font-bold">+ Ajouter</button>
            </div>
            <div class="grid grid-cols-5 gap-4">
                \${state.content.map(c => \`
                    <div class="relative group aspect-[2/3] bg-neutral-800 rounded overflow-hidden">
                        <img src="\${c.posterUrl}" class="w-full h-full object-cover">
                        <button onclick="deleteContent('\${c.id}')" class="absolute top-2 right-2 bg-red-600 p-2 rounded-full opacity-0 group-hover:opacity-100 transition"><i data-lucide="trash-2" width="16"></i></button>
                    </div>
                \`).join('')}
            </div>
        \`;
    } else if (state.activeTab === 'USERS') {
        p.innerHTML = \`
            <h2 class="text-3xl font-bold mb-6">Abonnés</h2>
            <table class="w-full text-left bg-black rounded overflow-hidden">
                <thead class="bg-neutral-800 text-neutral-400"><tr><th class="p-4">Nom</th><th class="p-4">Preuve</th><th class="p-4">Fin</th><th class="p-4">Action</th></tr></thead>
                <tbody>
                    \${state.users.map(u => \`
                        <tr class="border-t border-neutral-800">
                            <td class="p-4">\${u.name} <span class="text-xs ml-2 px-2 py-0.5 rounded \${u.status==='ACTIVE'?'bg-green-900 text-green-400':'bg-yellow-900 text-yellow-400'}">\${u.status}</span></td>
                            <td class="p-4">\${u.paymentProof || '-'}</td>
                            <td class="p-4">\${u.subscriptionEnd ? new Date(u.subscriptionEnd).toLocaleDateString() : '-'}</td>
                            <td class="p-4">
                                \${u.status !== 'ACTIVE' ? \`<button onclick="activateUser('\${u.id}')" class="bg-[#00CEC8] text-black px-3 py-1 rounded font-bold text-sm">VALIDER</button>\` : \`<button onclick="banUser('\${u.id}')" class="text-red-500 text-sm font-bold">STOP</button>\`}
                            </td>
                        </tr>
                    \`).join('')}
                </tbody>
            </table>
        \`;
    } else if (state.activeTab === 'THEME') {
        p.innerHTML = \`
             <h2 class="text-3xl font-bold mb-6">Options</h2>
             <div class="mb-6">
                <label class="block mb-2">Lien Communauté</label>
                <div class="flex gap-2">
                    <input id="comm-link" value="\${state.communityLink}" class="bg-black p-3 rounded w-full border border-neutral-700">
                    <button onclick="saveComm()" class="bg-[#00CEC8] text-black px-4 rounded font-bold">Save</button>
                </div>
             </div>
        \`;
    }
    lucide.createIcons();
}

window.openAddModal = () => {
    const d = document.createElement('div');
    d.className = 'fixed inset-0 bg-black/80 flex items-center justify-center z-50';
    d.innerHTML = \`
        <div class="bg-neutral-900 p-8 rounded-xl w-full max-w-lg border border-neutral-700">
            <h3 class="text-xl font-bold mb-4">Ajouter</h3>
            <input id="n-title" placeholder="Titre" class="w-full bg-black p-3 mb-3 rounded border border-neutral-700 text-white">
            <select id="n-type" class="w-full bg-black p-3 mb-3 rounded border border-neutral-700 text-white">
                <option value="MOVIE">Film</option>
                <option value="SERIES">Série</option>
            </select>
            <input id="n-poster" placeholder="URL Affiche" class="w-full bg-black p-3 mb-3 rounded border border-neutral-700 text-white">
            <input id="n-video" placeholder="URL Vidéo" class="w-full bg-black p-3 mb-3 rounded border border-neutral-700 text-white">
            <textarea id="n-desc" placeholder="Description" class="w-full bg-black p-3 mb-3 rounded border border-neutral-700 text-white"></textarea>
            <div class="flex justify-end gap-2">
                <button onclick="this.closest('.fixed').remove()" class="text-neutral-500 font-bold">Annuler</button>
                <button onclick="saveContent()" class="bg-[#00CEC8] text-black px-6 py-2 rounded font-bold">Ajouter</button>
            </div>
        </div>
    \`;
    document.body.appendChild(d);
};

window.saveContent = () => {
    const title = document.getElementById('n-title').value;
    const type = document.getElementById('n-type').value;
    const poster = document.getElementById('n-poster').value || "https://placehold.co/400x600?text=No+Image";
    const video = document.getElementById('n-video').value;
    const desc = document.getElementById('n-desc').value;
    
    if(!title) return;
    
    state.content.push({ 
        id: Date.now().toString(), 
        title, type, posterUrl: poster, videoUrl: video, description: desc, 
        genres: ['Action'], releaseYear: '2024', rating: 'NEW', cast: [], episodes: [] 
    });
    db.save('content');
    document.querySelector('.fixed').remove();
    render();
};

window.deleteContent = (id) => { state.content = state.content.filter(c => c.id !== id); db.save('content'); render(); };
window.activateUser = (id) => { 
    const u = state.users.find(x => x.id === id); 
    if(u) { u.status = 'ACTIVE'; u.plan = 'PREMIUM'; u.subscriptionEnd = new Date(Date.now() + 30*24*60*60*1000).toISOString(); db.save('users'); render(); } 
};
window.banUser = (id) => { const u = state.users.find(x => x.id === id); if(u) { u.status = 'BANNED'; db.save('users'); render(); } };
window.saveComm = () => { state.communityLink = document.getElementById('comm-link').value; db.save('community'); render(); };
window.previewSite = () => { state.user = { id: 'admin-preview', name: 'Admin', status: 'ACTIVE', email: 'prev@vtv.com' }; render(); };

// --- USER UI ---
function renderUser() {
    if(state.user.status !== 'ACTIVE') {
        app.innerHTML = \`<div class="h-screen flex flex-col items-center justify-center p-6 text-center">
            <h1 class="text-6xl font-black text-[#00CEC8] mb-4">VTV</h1>
            <h2 class="text-2xl font-bold mb-4">Abonnement requis</h2>
            <div class="grid gap-4 w-full max-w-md">\${Object.keys(PLANS).map(k => \`<button onclick="sub('\${k}')" class="bg-neutral-800 p-4 rounded border border-neutral-700 hover:border-[#00CEC8]"><div>\${PLANS[k].name}</div><div class="text-[#00CEC8] font-bold">\${PLANS[k].price}</div></button>\`).join('')}</div>
            <button onclick="logout()" class="mt-8 text-neutral-500">Déconnexion</button>
        </div><div id="modal"></div>\`;
        return;
    }

    const top10 = [...state.content].reverse().slice(0, 10);
    const filtered = state.searchQuery ? state.content.filter(c => c.title.toLowerCase().includes(state.searchQuery.toLowerCase())) : state.content;

    app.innerHTML = \`
        <nav class="fixed top-0 w-full z-50 bg-gradient-to-b from-black/90 to-transparent px-6 py-4 flex justify-between items-center">
            <div class="text-2xl font-black logo-shine cursor-pointer" onclick="state.searchQuery='';render()">VTV</div>
            <div class="flex items-center gap-4">
                \${state.communityLink ? \`<a href="\${state.communityLink}" target="_blank" class="bg-blue-600 px-3 py-1 rounded-full text-xs font-bold flex gap-1 items-center"><i data-lucide="users" width="12"></i> Communauté</a>\` : ''}
                <input oninput="state.searchQuery=this.value;render()" placeholder="Recherche..." class="bg-black/40 border border-neutral-700 rounded-full px-4 py-1 text-sm text-white w-32 focus:w-48 transition-all">
                <button onclick="logout()" class="text-sm font-bold opacity-70 hover:opacity-100">\${state.user.name}</button>
            </div>
        </nav>
        
        \${!state.searchQuery && state.content.length > 0 ? \`
            <header class="relative h-[70vh] flex items-end p-8 overflow-hidden">
                <img src="\${state.content[0].posterUrl}" class="absolute inset-0 w-full h-full object-cover opacity-60">
                <div class="absolute inset-0 bg-gradient-to-t from-neutral-950 via-transparent to-transparent"></div>
                <div class="relative z-10 max-w-2xl">
                    <h1 class="text-5xl font-black mb-4">\${state.content[0].title}</h1>
                    <p class="text-lg text-neutral-300 mb-6 line-clamp-3">\${state.content[0].description}</p>
                    <button onclick="play('\${state.content[0].id}')" class="bg-white text-black px-8 py-3 rounded font-bold flex items-center gap-2"><i data-lucide="play" class="fill-black"></i> Lecture</button>
                </div>
            </header>
            
            <div class="px-8 -mt-16 relative z-20 pb-20 space-y-12">
                <div>
                    <h3 class="text-xl font-bold mb-4 flex gap-2"><i data-lucide="trending-up" class="text-[#00CEC8]"></i> Top 10 Aujourd'hui</h3>
                    <div class="flex overflow-x-auto gap-4 scrollbar-hide pl-4 pb-4">
                        \${top10.map((c, i) => \`
                            <div onclick="play('\${c.id}')" class="flex-none w-[140px] relative cursor-pointer group transition-transform hover:scale-105">
                                <span class="absolute -left-4 bottom-0 text-[90px] font-black text-neutral-800 leading-none z-0">\${i+1}</span>
                                <img src="\${c.posterUrl}" class="w-full aspect-[2/3] object-cover rounded relative z-10 shadow-lg border border-neutral-800 group-hover:border-[#00CEC8]">
                            </div>
                        \`).join('')}
                    </div>
                </div>
                
                <div>
                    <h3 class="text-xl font-bold mb-4">Ajoutés Récemment</h3>
                    <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-4">
                        \${state.content.map(c => \`
                            <div onclick="play('\${c.id}')" class="aspect-[2/3] bg-neutral-800 rounded overflow-hidden relative group cursor-pointer border border-neutral-800 hover:border-[#00CEC8]">
                                <img src="\${c.posterUrl}" class="w-full h-full object-cover">
                                <div class="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity"><i data-lucide="play-circle" class="w-12 h-12 text-white"></i></div>
                            </div>
                        \`).join('')}
                    </div>
                </div>
            </div>
        \` : \`
            <div class="pt-24 px-8 min-h-screen">
                <h2 class="text-2xl font-bold mb-6">Résultats</h2>
                <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                    \${filtered.map(c => \`<div onclick="play('\${c.id}')" class="aspect-[2/3] bg-neutral-800 rounded overflow-hidden relative cursor-pointer"><img src="\${c.posterUrl}" class="w-full h-full object-cover"></div>\`).join('')}
                </div>
            </div>
        \`}
        <div id="player-modal"></div>
    \`;
    lucide.createIcons();
}

window.sub = (k) => {
    document.getElementById('modal').innerHTML = \`<div class="fixed inset-0 bg-black/90 flex items-center justify-center p-4"><div class="bg-neutral-900 p-8 rounded border border-neutral-700 w-full max-w-sm"><h3 class="font-bold mb-4">Paiement Mobile</h3><p class="mb-4">Envoyez \${PLANS[k].price} au <span class="text-[#00CEC8] font-mono">\${PAYMENT_NUMBER}</span></p><input id="prf" placeholder="ID Transaction" class="w-full bg-black p-3 mb-4 rounded border border-neutral-700 text-white"><button onclick="confSub('\${k}')" class="w-full bg-[#00CEC8] text-black font-bold py-3 rounded">Confirmer</button><button onclick="document.getElementById('modal').innerHTML=''" class="w-full mt-2 text-neutral-500">Annuler</button></div></div>\`;
};
window.confSub = (k) => {
    state.user.status='PENDING'; state.user.plan=k; state.user.paymentProof=document.getElementById('prf').value;
    const idx = state.users.findIndex(u => u.id === state.user.id); if(idx!==-1) state.users[idx] = state.user;
    db.save('users'); db.save('user'); render();
};

window.play = (id) => {
    const c = state.content.find(x => x.id === id);
    if(!c) return;
    document.getElementById('player-modal').innerHTML = \`
        <div class="fixed inset-0 z-[60] bg-black flex flex-col animate-fade-in">
            <div class="relative flex-1 bg-black flex items-center justify-center">
                <button onclick="document.getElementById('player-modal').innerHTML=''" class="absolute top-4 right-4 z-50 bg-black/50 p-2 rounded-full hover:bg-white hover:text-black"><i data-lucide="x"></i></button>
                <video src="\${c.videoUrl}" controls autoplay class="w-full h-full max-h-screen object-contain"></video>
            </div>
            <div class="p-8 bg-neutral-900">
                <h2 class="text-2xl font-bold">\${c.title}</h2>
                <p class="text-neutral-400 mt-2 max-w-3xl">\${c.description}</p>
            </div>
        </div>
    \`;
    lucide.createIcons();
};

db.load();
render();
`;

  zip.file("script.js", scriptJs);

  // Download
  const content = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(content);
  const a = document.createElement("a");
  a.href = url;
  a.download = "vtv-platform-complete.zip";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
